---
gui_alias: "ACI sandbox"
vlan_pool: metal_gear
aep: metal_gear
domain_name: metal_gear
domain_type: phys

ipg:
  access: single_apg
  vpc1: core-fw01_vpc
  vpc2: core-rt01_vpc
  direct1: nas01_direct
  direct2: nas02_direct

leaf_201:
  name: leaf-201
  swp:
    leaf_sel: leaf-201_sel
    node_block: one
    from: "201"
    to: "201"
  ifps:
    - ipg: "{{ ipg.direct1 }}"
      leaf_ifp: leaf-201_ifp
      acc_port_sel: "eth1_3-4_{{ ipg.direct1 }}"
      leaf_port_blk: block2
      from_port: "3"
      to_port: "4"
    - ipg: single_apg
      leaf_ifp: leaf-201_ifp
      acc_port_sel: "eth1_5_DD"
      leaf_port_blk: block2
      from_port: "5"
      to_port: "5"
    - ipg: single_apg
      leaf_ifp: leaf-201_ifp
      acc_port_sel: "eth1_6_CU"
      leaf_port_blk: block2
      from_port: "6"
      to_port: "6"
    - ipg: single_apg
      leaf_ifp: leaf-201_ifp
      acc_port_sel: "eth1_7_FOX"
      leaf_port_blk: block2
      from_port: "7"
      to_port: "7"

leaf_202:
  name: leaf-202
  swp:
    leaf_sel: leaf-202_sel
    node_block: two
    from: "202"
    to: "202"
  ifps:
    - ipg: "{{ ipg.direct2 }}"
      leaf_ifp: leaf-202_ifp
      acc_port_sel: "eth1_3-4_{{ ipg.direct2 }}"
      leaf_port_blk: block2
      from_port: "3"
      to_port: "4"
    - ipg: single_apg
      leaf_ifp: leaf-202_ifp
      acc_port_sel: "eth1_5_DD"
      leaf_port_blk: block2
      from_port: "5"
      to_port: "5"
    - ipg: single_apg
      leaf_ifp: leaf-202_ifp
      acc_port_sel: "eth1_6_CU"
      leaf_port_blk: block2
      from_port: "6"
      to_port: "6"
    - ipg: single_apg
      leaf_ifp: leaf-202_ifp
      acc_port_sel: "eth1_7_FOX"
      leaf_port_blk: block2
      from_port: "7"
      to_port: "7"

leaf_201_202:
  name: leaf-201_202
  swp:
    leaf_sel: leaf-201_202_sel
    node_block: three
    from: 201
    to: 202
  ifps:
    - ipg: core-fw01_vpc
      leaf_ifp: leaf-201_202_ifp
      acc_port_sel: "eth1_1_core-fw01"
      leaf_port_blk: block2
      from_port: "1"
      to_port: "1"
    - ipg: core-rt01_vpc
      leaf_ifp: leaf-201_202_ifp
      acc_port_sel: "eth1_2_core-rt01"
      leaf_port_blk: block2
      from_port: "2"
      to_port: "2"

tenants:
  - tenant: DiamondDogs
    encaps_block: DiamondDogs
    block_start: 660
    block_end: 669
    vrf: DD_vrf
    bd: DD_bd
    ap: DD_ap
    epg: DD_epg
    descr: "Created by Ansible for Diamond Dogs"
    static_paths:
      - leafs: 201
        tenant: DiamondDogs
        bd: DD_bd
        ap: DD_ap
        epg: DD_epg
        intf_type: switch_port
        intf: "1/5"
        intf_mode: untagged
        encap_id: 666
        immediacy: immediate
        pod_id: 1
      - leafs: 201
        tenant: DiamondDogs
        bd: DD_bd
        ap: DD_ap
        epg: DD_epg
        intf_type: port_channel
        intf: "{{ leaf_201.ifps[0].acc_port_sel }}"
        intf_mode: tagged
        encap_id: 666
        immediacy: immediate
        pod_id: 1
      - leafs: 202
        tenant: DiamondDogs
        bd: DD_bd
        ap: DD_ap
        epg: DD_epg
        intf_type: switch_port
        intf: "1/5"
        intf_mode: 802.1p
        encap_id: 666
        immediacy: immediate
        pod_id: 1
      - leafs: 202
        tenant: DiamondDogs
        bd: DD_bd
        ap: DD_ap
        epg: DD_epg
        intf_type: port_channel
        intf: "{{ leaf_202.ifps[0].acc_port_sel }}"
        intf_mode: tagged
        encap_id: 666
        immediacy: immediate
        pod_id: 1
      - leafs: 201-202
        tenant: DiamondDogs
        bd: DD_bd
        ap: DD_ap
        epg: DD_epg
        intf_type: vpc
        intf: "{{ leaf_201_202.ifps[0].acc_port_sel }}"
        intf_mode: tagged
        encap_id: 666
        immediacy: immediate
        pod_id: 1
      - leafs: 201-202
        tenant: DiamondDogs
        bd: DD_bd
        ap: DD_ap
        epg: DD_epg
        intf_type: vpc
        intf: "{{ leaf_201_202.ifps[1].acc_port_sel }}"
        intf_mode: tagged
        encap_id: 666
        immediacy: immediate
        pod_id: 1

  - tenant: CobraUnit
    encaps_block: CobraUnit
    block_start: 670
    block_end: 679
    vrf: Cobra_vrf
    bd: Cobra_bd
    ap: Cobra_ap
    epg: Cobra_epg
    descr: "Created by Ansible for Diamond Dogs"
    static_paths:
      - leafs: 201
        tenant: CobraUnit
        ap: Cobra_ap
        epg: Cobra_epg
        intf_type: switch_port
        intf: "1/6"
        intf_mode: untagged
        encap_id: 677
        immediacy: immediate
        pod_id: 1
      - leafs: 201
        tenant: CobraUnit
        ap: Cobra_ap
        epg: Cobra_epg
        intf_type: port_channel
        intf: "{{ leaf_201.ifps[0].acc_port_sel }}"
        intf_mode: tagged
        encap_id: 677
        immediacy: immediate
        pod_id: 1
      - leafs: 202
        tenant: CobraUnit
        ap: Cobra_ap
        epg: Cobra_epg
        intf_type: switch_port
        intf: "1/6"
        intf_mode: 802.1p
        encap_id: 677
        immediacy: immediate
        pod_id: 1
      - leafs: 202
        tenant: CobraUnit
        ap: Cobra_ap
        epg: Cobra_epg
        intf_type: port_channel
        intf: "{{ leaf_202.ifps[0].acc_port_sel }}"
        intf_mode: tagged
        encap_id: 677
        immediacy: immediate
        pod_id: 1
      - leafs: 201-202
        tenant: CobraUnit
        ap: Cobra_ap
        epg: Cobra_epg
        intf_type: vpc
        intf: "{{ leaf_201_202.ifps[0].acc_port_sel }}"
        intf_mode: tagged
        encap_id: 677
        immediacy: immediate
        pod_id: 1
      - leafs: 201-202
        tenant: CobraUnit
        ap: Cobra_ap
        epg: Cobra_epg
        intf_type: vpc
        intf: "{{ leaf_201_202.ifps[1].acc_port_sel }}"
        intf_mode: tagged
        encap_id: 677
        immediacy: immediate
        pod_id: 1

  - tenant: FOX
    encaps_block: FOX
    block_start: 680
    block_end: 689
    vrf: Fox_vrf
    bd: Fox_bd
    ap: Fox_ap
    epg: Fox_epg
    descr: "Created by Ansible for FOX Unit"
    static_paths:
      - leafs: 201
        tenant: FOX
        ap: Fox_ap
        epg: Fox_epg
        intf_type: switch_port
        intf: "1/7"
        intf_mode: untagged
        encap_id: 688
        immediacy: immediate
        pod_id: 1
      - leafs: 202
        tenant: FOX
        ap: Fox_ap
        epg: Fox_epg
        intf_type: switch_port
        intf: "1/7"
        intf_mode: 802.1p
        encap_id: 688
        immediacy: immediate
        pod_id: 1
      - leafs: 201-202
        tenant: FOX
        ap: Fox_ap
        epg: Fox_epg
        intf_type: vpc
        intf: "{{ leaf_201_202.ifps[0].acc_port_sel }}"
        intf_mode: tagged
        encap_id: 688
        immediacy: immediate
        pod_id: 1
      - leafs: 201-202
        tenant: FOX
        ap: Fox_ap
        epg: Fox_epg
        intf_type: vpc
        intf: "{{ leaf_201_202.ifps[1].acc_port_sel }}"
        intf_mode: tagged
        encap_id: 688
        immediacy: immediate
        pod_id: 1
